name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ macos-latest ]
          rust: [ stable ]

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'

    - name: build-mac
      if: matrix.os == 'macos-latest'
      run: flutter build macos

    - name: build-mac
      if: matrix.os == 'macos-latest'
      run: flutter build web

    - name: test
      run: flutter test